### ISSUE TITLE
Without binarizing the downsample layer for ResNet on ImageNet

### ISSUE THREAD

**Issue by liyunqianggyn** [htqin/IR-Net#10]
Nice work!!! Thank you for sharing the code. When i check the code, I found that the downsample layers for ResNet on ImageNet are not binarized to 1-bit values. Is that correct? In Cifar10, the downsample layer is quantized?

**Comment by htqin** [comment]
Hey @liyunqianggyn , I think the problem started in #7 . We follow the setting of Bi-Real Net for fair comparison.
