### ISSUE TITLE
Questions about training

### ISSUE THREAD

**Issue by sleeplessai** [htqin/IR-Net#12]
Hi, author team,
After reading your paper and codes, I wonder that how to train the networks prototypes.
The training code are important for reproduction, please release them later. Thanks a lot for that. :+1: 
As you proposed in paper, the EDE and Libra-PB are both benefit the network performance, in that I am curious how to train.

**Comment by htqin** [comment]
Thanks for your attention. Just clone this project, then run main.py/trainer.py in folders.
