### ISSUE TITLE
k和t根本不会更新吧

### ISSUE THREAD

**Issue by pppLang** [htqin/IR-Net#18]
https://github.com/htqin/IR-Net/blob/f63a5901d02836e2cf4405da1c68e066353a025f/ImageNet/ResNet18/1w1a/models/modules/binaryfunction.py#L16

这样写的话，给k和t返回的梯度都是None，根本不会更新吧

**Comment by htqin** [comment]
https://github.com/htqin/IR-Net/blob/f63a5901d02836e2cf4405da1c68e066353a025f/CIFAR-10/ResNet20/1w1a/trainer.py#L145
