### ISSUE TITLE
Error about devices

### ISSUE THREAD

**Issue by BooguTeam** [htqin/IR-Net#19]
grad_input = k * t * (1 - torch.pow(torch.tanh(input * t), 2)) * grad_output

Expected all tensors to be on the same device, but found at least two devices , cuda:1 and cuda:0!

**Comment by ghost** [comment]
Do you solve the problem? I got the same error too. I believe that input in device1 and k,t in device0.We don't actually update kt in data parallel

**Comment by ghost** [comment]
It seems that you can send the tensor to device(input device) when the model forward.
