### ISSUE TITLE
The value of k and t

### ISSUE THREAD

**Issue by huangdi95** [htqin/IR-Net#3]
Hi,
I'm following your brilliant work and thanks for your sharing.
However, I found that the parameter 'k' and 't' in ir_1w1a.py seems fixed, which is not the same as the one in your paper.
Will this difference matter?

**Comment by dinghuanghao** [comment]
I encountered the same problem，It should be that the EDE related code is not open source

**Comment by killawhale2** [comment]
Same, I was also wondering why the values are fixed. Perhaps the authors found that the fixing the values of k and t does not matter much? Would be great to hear more details on this.

**Comment by htqin** [comment]
The values of k and t are updated in main.py or trainer.py.
e.g.: https://github.com/htqin/IR-Net/blob/master/CIFAR-10/ResNet20/1w32a/trainer.py#L139

**Comment by brisker** [comment]
@htqin
I can not find any code corresponding to the information entropy therory discussed in your paper. Does this mean that, actually 
you did not use this information entropy loss in your model training??
