### ISSUE TITLE
Downsample quantization

### ISSUE THREAD

**Issue by brianchmiel** [htqin/IR-Net#7]
Hi,

I read your paper, where you wrote that you binarize all convolutional and fc layer except the first and last one.
However, I see from your code that also the downsample convolution aren't quantized (They are not replaced with IRConv2d - e.g https://github.com/htqin/IR-Net/blob/master/CIFAR-10/ResNet18/resnet.py#L28) . What am I missing?

Thank you

**Comment by htqin** [comment]
Thanks for your attention! We follow the setting of Bi-Real Net for fair comparison.
https://github.com/liuzechun/Bi-Real-net/blob/master/pytorch_implementation/BiReal18_34/birealnet.py#L110
