### ISSUE TITLE
ResNet34

### ISSUE THREAD

**Issue by zhaoguochuan** [htqin/IR-Net#9]
hello，thank you for your work!
I got a model of size 81.3MB when I used the resnet.py file in your "IR-Net-master\ImageNet\ResNet34\1w1a\models"directory.
This is the same size as my model using the full precision ResNet34 network.
How do I compress my model?

**Comment by htqin** [comment]
Email has been replied.
The deployment of IR-Net should combine the existing high-performance inference frameworks such as dabnn.
